### ISSUE TITLE
Add "positive" message explaining the issue

### ISSUE THREAD

**Issue by chevdor** [chevdor/ruled_labels#3]
Instead of "FAILED  Release require some topics" is would be nice to render the rule to tell the user what exactly neesd to be done and why.

For instance in that case:
```
  - name: Release require some topics
    when: !one_of [ B1 ]
    spec:
      require: !some_of [ X* ]
```

We could output:
> Since you have **one** `B1`, please make sure to add **some** `X` labels.
